<?php

namespace MinimalOriginal\RelatedBundle\Repository;

/**
 * RelatedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelatedRepository extends \Doctrine\ORM\EntityRepository
{
}
